server {
    # Just serve the content for any hostname
    # Let the ingress controller worry about that
    listen       8080 default_server;
    server_name  _;

    # All files should be served from the content directory
    # Unknown URLs should fallback to index.html so that applications using
    # the HTML5 history API can manipulate URLs that do not exist on the server
    location / {
        root /var/www/content;
        try_files $uri /index.html;
    }
}
